INSERT INTO AUTHOR(ID, PRENAME, SURNAME)VALUES(1, 'Stephen', 'King');
INSERT INTO AUTHOR(ID, PRENAME, SURNAME)VALUES(2, 'William', 'Shakespeare');
INSERT INTO AUTHOR(ID, PRENAME, SURNAME)VALUES(3, 'Algernon', 'Blackwood');
INSERT INTO AUTHOR(ID, PRENAME, SURNAME)VALUES(4, 'Edgar Allan', 'Poe');
INSERT INTO AUTHOR(ID, PRENAME, SURNAME)VALUES(5, 'Howard Phillips', 'Lovecraft');

INSERT INTO BOOK(ID, TITLE, AUTHOR)VALUES(1, 'The Shining1', 1);
INSERT INTO BOOK(ID, TITLE, AUTHOR)VALUES(2, 'Pet Sematary1', 1);
INSERT INTO BOOK(ID, TITLE, AUTHOR)VALUES(3, 'Christine', 1);
INSERT INTO BOOK(ID, TITLE, AUTHOR)VALUES(4, 'Der Wendigo', 3);
INSERT INTO BOOK(ID, TITLE, AUTHOR)VALUES(5, 'Der Rabe', 4);
INSERT INTO BOOK(ID, TITLE, AUTHOR)VALUES(6, 'Cthulhus Ruf', 5);
INSERT INTO BOOK(ID, TITLE, AUTHOR)VALUES(7, 'Das Grauen von Dunwich', 5);
INSERT INTO BOOK(ID, TITLE, AUTHOR)VALUES(8, 'Hamlet', 2);
INSERT INTO BOOK(ID, TITLE, AUTHOR)VALUES(9, 'König Lear', 2);
INSERT INTO BOOK(ID, TITLE, AUTHOR)VALUES(10, 'Die Schwarze Katze', 4);
INSERT INTO BOOK(ID, TITLE, AUTHOR)VALUES(11, 'Annabel Lee', 4);
INSERT INTO BOOK(ID, TITLE, AUTHOR)VALUES(12, 'The Willows', 3);



